max_width = 90
indent_size = 4
hard_tabs = false
tab_spaces = 4
emit_mode = "NewFile"
verbose = "Verbose"
prefer_one_line_for_short_branch_blk = true
prefer_one_line_for_short_call_para_list = true
prefer_one_line_for_short_fn_header_para_list = true
prefer_one_line_for_short_lambda_para_list = true
skip_formatting_dirs = "doc;tests;/home/xx/yy/zz"
auto_apply_package = true