[package]
name = "configurations"
version = "1.6.1"
description = "configurations"
edition = "2021"

[dependencies]
annotate-snippets = { version = "0.9", features = ["color"] }
anyhow = "1.0"
diff = "0.1"
dirs = "4.0"
getopts = "0.2"
ignore = "0.4"
itertools = "0.10"
lazy_static = "1.4"
regex = "1.7"
serde = { version = "1.0.160", features = ["derive"] }
thiserror = "1.0.40"
toml = "0.7.4"
tracing = "0.1.37"
unicode-segmentation = "1.9"
unicode-width = "0.1"
unicode-properties = { version = "0.1", default-features = false, features = ["general-category"] }

config_proc_macro = { version = "0.3", path = "config_proc_macro" }

