[package]
name = "config_proc_macro"
version = "0.3.1"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "visit"] }

[dev-dependencies]
serde = { version = "1.0.160", features = ["derive"] }

[features]
default = []